apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment-$id
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-deploy-$id
  template:
    metadata:
      labels:
        app: example-deploy-$id
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - kwok
      # A taint was added to an automatically created Node.
      # You can remove taints of Node or add this toleration.
      tolerations:
        - key: "kwok.x-k8s.io/node"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
      - name: example-deploy-$id
        image: example-deploy:1.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
