apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fake-hpa-$id
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: example-$id
  minReplicas: 1
  maxReplicas: 10
