apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-$id
  namespace: default
subjects:
- kind: User
  name: user-$id
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader-$id
  apiGroup: rbac.authorization.k8s.io

